// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2EjnTScRlh7bwnog1xg-N8EvX2fC5dr8',
    appId: '1:422680142561:web:38329792bbd20e62a4cda0',
    messagingSenderId: '422680142561',
    projectId: 'sms-flutter-c6d80',
    authDomain: 'sms-flutter-c6d80.firebaseapp.com',
    storageBucket: 'sms-flutter-c6d80.firebasestorage.app',
    measurementId: 'G-HFM8M1ML13',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAedFXNpMjMENEZ3nq3L0q6xvPTsdJeBb8',
    appId: '1:422680142561:android:27b4de94baf95073a4cda0',
    messagingSenderId: '422680142561',
    projectId: 'sms-flutter-c6d80',
    storageBucket: 'sms-flutter-c6d80.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6jP1J7bjuS72AOqtqdGdvW9sTINo0V9c',
    appId: '1:422680142561:ios:f64b74ce4d9b1615a4cda0',
    messagingSenderId: '422680142561',
    projectId: 'sms-flutter-c6d80',
    storageBucket: 'sms-flutter-c6d80.firebasestorage.app',
    iosBundleId: 'techbros.sms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6jP1J7bjuS72AOqtqdGdvW9sTINo0V9c',
    appId: '1:422680142561:ios:1806fa21584a425ea4cda0',
    messagingSenderId: '422680142561',
    projectId: 'sms-flutter-c6d80',
    storageBucket: 'sms-flutter-c6d80.firebasestorage.app',
    iosBundleId: 'com.techbros.sms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2EjnTScRlh7bwnog1xg-N8EvX2fC5dr8',
    appId: '1:422680142561:web:1bdce4dfdfa84df3a4cda0',
    messagingSenderId: '422680142561',
    projectId: 'sms-flutter-c6d80',
    authDomain: 'sms-flutter-c6d80.firebaseapp.com',
    storageBucket: 'sms-flutter-c6d80.firebasestorage.app',
    measurementId: 'G-RQQD92V8YE',
  );

}