name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - master  # 👈 Trigger only when code is pushed to 'master'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'  # or use your actual version

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter web
        run: flutter build web

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
          publish_branch: gh-pages
          force_orphan: true
